### ISSUE TITLE
Impossible to use in multiplayer

### ISSUE THREAD

**Issue by bobzap** [gruppe-adler/grad-listBuymenu#17]
Hello !! 

At first I would like to thank you for your incredible scripts !! 

But I have a problem with this one. 
When I play in solo the seller can find the money that I have on me. 
But in multiplayers, the seller don't find my monney. It's wrote : 0 Cr 

Have you the solution ? 

thank's in advance ;)

**Comment by klemmchr** [comment]
Show us your code your are using to add the money.

**Comment by bobzap** [comment]
I paste this one, on the description.text

class CfgGradMoneymenu {
    canGiveDefault = 1;                                                    
    canTransferToSidesDefault[] = {"east","west","independent","civilian"};
    canTakeFromDeadDefault = 1;        
    canSendDirectlyDefault = 0;                                    
    canTakeFromSurrenderedDefault = 1;
    canGiveToAI = 1;                              
    startMoney = 2000;                                                        
    startBankBalance = 2000;                                                  
    atmObjects[] = {"Land_Atm_01_F"};

**Comment by klemmchr** [comment]
Do you get any config errors? Easiest way to track down the issue would be to zip your mission and attach it here.

**Comment by bobzap** [comment]
No error :/ 
you can find my mission with this links 

[TestGRADadler.zip](https://github.com/gruppe-adler/grad-listBuymenu/files/1595103/TestGRADadler.zip)

**Comment by bobzap** [comment]
You need CBA_A3 / ACE / CUP terrain core  / CUP terrain map 
The seller is the second soldier.

May be you can send me your Multiplayer mission ?

**Comment by McDiod** [comment]
pretty sure this was fixed in some update or something
