### ISSUE TITLE
Wetsuit and Racing gear won't spawn when bought.

### ISSUE THREAD

**Issue by Maseddu** [gruppe-adler/grad-listBuymenu#18]
Wetsuit and Racing gear won't spawn when bought, not in the inventory and neither in the cargoholder box.
ITEMS CLASSNAME:
Item_U_B_Wetsuit
Item_U_C_Driver_1_black (all colors)
Headgear_H_RacingHelmet_1_black_F (all colors)
Any ideas why?
The interaction go well,  the money are working too...
The other object in the same list work.
If needed i can provide the description file.

**Comment by McDiod** [comment]
Use these instead:

```
U_B_Wetsuit
U_C_Driver_1_black
H_RacingHelmet_1_black_F
```

Yours is the CfgVehicles version of those items, the above is CfgWeapons.

**Comment by Maseddu** [comment]
> Use these instead:
> 
> ```
> U_B_Wetsuit
> U_C_Driver_1_black
> H_RacingHelmet_1_black_F
> ```
> Yours is the CfgVehicles version of those items, the above is CfgWeapons.

Thank you!
