### ISSUE TITLE
Sell ?

### ISSUE THREAD

**Issue by psvialli** [gruppe-adler/grad-listBuymenu#21]
There is no way to sell items back ?

**Comment by McDiod** [comment]
correct

**Comment by psvialli** [comment]
Will you be adding this in at some point or is this not designed for that ?

**Comment by McDiod** [comment]
We don't really have a use case for it, so while it would be possible to add I'm not planning on doing so in the near future.

**Comment by psvialli** [comment]
NP many thanks it is awesome BTW :)
