### ISSUE TITLE
UAV's, drones and buying units

### ISSUE THREAD

**Issue by BrianV1981** [gruppe-adler/grad-listBuymenu#22]
Hello,
Great work on the last update! I am now dropping money on death.

I am having problems with purchasing/selling UAV's and drones. They do not spawn with a crew in them. I did try to place them for sale in the "Units" category with no luck.

I initially misread your configuration for "spawnEmpty" and assumed that was to spawn the vehicle without a crew inside (commander, gunner, driver). However, I see that is actually an option to have the vehicle's cargo emptied when spawned.

I think it would be helpful to have a "crew" option for the vehicle category. I believe that I could figure out how to utilize the "Other" category to accomplish what I am after, but I figured I would write up this suggestion :)

**Comment by McDiod** [comment]
Hi,

```
code = "if (isServer) then {createVehicleCrew (_this select 2)}";
```

should work.

See also:
https://github.com/gruppe-adler/grad-listBuymenu/wiki/Configuration#code

**Comment by BrianV1981** [comment]
Thank you, that is exactly what I was looking for! You wouldn't happen to have a code snippet to have purchased units/soldiers join the customers' group, would you? Until your response, I thought that would be another good configuration option, but I think I may be in over my head with respect to the code aspect.

**Comment by McDiod** [comment]
> a code snippet to have purchased units/soldiers join the customers' group

Try

```sqf
code = "if (isServer) then {(units (_this select 2)) joinSilent (_this select 0)}";
```

**Comment by BrianV1981** [comment]
Hello McDiod! I just wanted to say thank you. The code to have purchased units join the customers' group does work, however, when the store gets to "big" there seems to be an issue. The units attempt to join, but then immediately leave the group and continue to follow the customer, but do not take orders. Some of the purchased units did not even attempt to join and would just stand where they spawned in.

I did some digging and came across a few "workarounds", they may not be perfect, but I wanted to share them here with the hopes that it may help someone else. :)

Example 1: [Spawning Units in Multiplayer / Dedicated Server](https://forums.bohemia.net/forums/topic/190594-spawning-units-in-multiplayer-dedicated-server/)

Example 2: [What AI Recruitment Scripts do you use](https://forums.bohemia.net/forums/topic/187333-what-ai-recruitment-scripts-do-you-use/)

In "Example 2" it shows 2 scripts that would allow the player to walk up to any unit and invite them to join their group. 

I ended up utilizing the "other" category in the grad-listBuymenu and using a script to spawn in the unit and to have it join the customer's group, identical to "Example 1".

**Comment by McDiod** [comment]
> when the store gets to "big" there seems to be an issue

Interesting. Store getting too "big" meaning you have too many items that the customer can buy, or you are buying too many units at once?

**Comment by BrianV1981** [comment]
The actual amount of items on the store seemed to be the ultimate problem. I spent quite a bit of time trying to get over that hurdle :)

 It worked great initially, then as the store menu got bigger, I noticed the units would not join the customers' group every so often...I didn't think much of it and chalked it up to lag or possibly clicking "buy" to fast. Well, the store continued to grow and the problem got worse. It took a while to figure that out :)

Then, I decided to split the store up into multiple "stores", each with its own file. I used the TvT UrbanOps store as my example. The problem persisted...

I then shrank the story down and found the "working" size, but at that point, I had to figure out how not to remove half of my store :) So, I came across a solution that I mentioned above.

I have read that executing .sqf files during the mission is not a good idea, but, it works for now :) I have an example mission [here](https://github.com/BrianV1981/arma3gradTesting) that anybody can check out to see how I ended up spawning in the units and have them join the customers' group on a dedicated server. If you do actually take a look, I invite any and all critiques!

While I have your attention, maybe you can answer a question that I can not seem to figure out. This pertains to the "other" category as well.

I use the "other" category to sell grad-fortifications. It works perfect on single-player and multiplayer testing when the customer purchases 1 item, 1 item spawns in, however, on a dedicated server, it spawns 2 items for every single purchase. 

```
class Land_BagFence_Corner_F {
                displayName = "Sandbag Wall (Corner)";
                description = "Sandbag Wall (Corner) can be built with the ACE Self Interaction Menu > Equipment > Fortifications.";
                price = 10;
                stock = 200;
				code = [container_1,"Land_BagFence_Corner_F"] call grad_fortifications_fnc_addFort;
```

here is another example that I have the same problem, on a dedicated server, it executes CAS1.sqf twice for every single purchase

```
class B_Heli_Attack_01_F {
                displayName = "ALiVE RAH-66 Comanche Combat Support (30 Minutes)";
                description = "Purchasing this will give you 30 minutes of access to a RAH-66 Comanche combat support helicopter, that can be utilized from your Ace Self Interact Menu > ALiVE > ALiVE Combat Support.";
                price = 75000;
                stock = 100;
		code = _handle = [] execVM "scripts\CAS1.sqf";
```

I figure it is because it is executing code on the server and locally, but I can not figure out how to execute store-bought items only on the server or only locally. Any help would be greatly appreciated.

**Comment by McDiod** [comment]
Do you still have the version where the shop was too big? I'd be interested to take a look.

***

Code is always executed both on server and on the client that bought the thing. The buyer is passed as the first parameter to the code (the subsequent parameters might differ from type to type). 

To execute code on server only:

```sqf
code = "if (isServer) then { */ your code /*}";
```

To execute code on buyer only:

```sqf
code = "if (player == (_this select 0)) then { */ your code /*}";
```

**Comment by BrianV1981** [comment]
I just recreated it with my current [arma3gradTesting](https://github.com/BrianV1981/arma3gradTesting) repository. If you grab the `oldMercenaryStoreMenu.hpp` from the modules folder of that repository and slide it into anyone of your larger stores, it should reproduce the same problem.

However, I added 4 .pbo's to the above repository. v3, 4, 5, and 6. 

- arma3gradTesting_v003.altis.pbo (my current version - can not figure out how to save storage across disconnects and restarts)
- arma3gradTesting_v004.altis.pbo (added oldMercenaryStoreMenu.hpp to the store)
- arma3gradTesting_v005.altis.pbo (removed vehicle store)
- arma3gradTesting_v006.altis.pbo (removed weapon and item store.)

Version 4, you will be lucky to get a unit to join your group unless you spam the buy button. Version 5 didn't seem much better, so I just went ahead and chopped off 2 more stores for version 6. Now, in version 6, if you continue buying units, it will reproduce the same exact bug. Just not as bad as in versions 4 and 5. In version 6, you have to buy anywhere from 60-100 guys before you can see it happen only a few times.

I would also like to mention that I believe this problem is directly related to a dedicated server. I cannot reproduce this in single or multiplayer. I hope there is some validity to what I have said, lol. I really enjoy creating missions, but I do a lot ( I mean a ton) of trial and error :)

**Comment by BrianV1981** [comment]
> Code is always executed both on server and on the client that bought the thing. The buyer is passed as the first parameter to the code (the subsequent parameters might differ from type to type).
> 
> To execute code on server only:
> 
> ```sqf
> code = "if (isServer) then { */ your code /*}";
> ```
> 
> To execute code on buyer only:
> 
> ```sqf
> code = "if (player == (_this select 0)) then { */ your code /*}";
> ```

I have tried 

`code = "if (isServer) then {[container_1,"Land_BagFence_Corner_F"] call grad_fortifications_fnc_addFort}";`

and 

`code = "if (player == (_this select 0)) then {[container_1,"Land_BagFence_Corner_F"] call grad_fortifications_fnc_addFort}";`

I have also tried 

`code = "if (isServer) then {execVM "script.sqf"}";`

and

`code = "if (player == (_this select 0)) then {execVM "script.sqf"}";`

with no luck. It keeps giving me errors. 

```
18:48:41 File C:\Users\kingb\Documents\Arma 3 - Other Profiles\Vasquez\mpmissions\arma3mercenaries_v003.Altis\modules\fortificationStoreMenu_1.hpp, line 39: '/CfgGradBuymenu/fortificationStore_1/fortifications_1/Land_BagFence_Corner_F.code': Missing ';' at the end of line
18:48:41 Error context ] call grad_fortifications_fnc_addFort}";
18:48:41 Warning Message: File C:\Users\kingb\Documents\Arma 3 - Other Profiles\Vasquez\mpmissions\arma3mercenaries_v003.Altis\modules\fortificationStoreMenu_1.hpp, line 39: '/CfgGradBuymenu/fortificationStore_1/fortifications_1/Land_BagFence_Corner_F.Land_BagFence_Corner_F': '"' encountered instead of '='
18:48:41 Warning Message: Config : some input after EndOfFile.
18:48:41 Class  destroyed with lock count 1
```

any help is appreciated.

**Comment by McDiod** [comment]
> If you want to include double quotes (") in strings enclosed by double quotes, the inside double quotes have to be written twice.

```sqf
_string = "my string ""with"" quotes";
_string2 = 'my other string "with" quotes';
```

**Comment by BrianV1981** [comment]
> > If you want to include double quotes (") in strings enclosed by double quotes, the inside double quotes have to be written twice.
> 
> ```sqf
> _string = "my string ""with"" quotes";
> _string2 = 'my other string "with" quotes';
> ```

Thank you! 

`code = "if (isServer) then {[container_1,'Land_BagFence_Corner_F'] call grad_fortifications_fnc_addFort}";`

`code = "if (player == (_this select 0)) then {[container_1,'Land_BagFence_Corner_F'] call grad_fortifications_fnc_addFort}";
`

`code = "if (isServer) then {execVM 'script.sqf'}";`

`code = "if (player == (_this select 0)) then {execVM 'script.sqf'}";`

Lesson learned :)
