### ISSUE TITLE
question

### ISSUE THREAD

**Issue by xzagrx** [gruppe-adler/grad-listBuymenu#23]
well i have a really simple question because i'm a bit dumb :D how to add two or more items in description, i wanted to setup my buy menu but i'm stuck... here is what i've got right now, for some reason i can't add lee enfield

```sqf
class CfgGradBuymenu {
    vehicleMarkers = 1;
    tracking = 1;
    trackingTag = "fap";
  //a different set of buyables
    class EDA {        
        class Items {
            displayName = "Items";
            kindOf = "Items";
			
			//items of this category:
            class ACE_fieldDressing {
                displayName = "Bandages (x10)";
                description = "10 simple bandages in sterile packaging.";
                amount = 10;
                price = 1000;
                stock = 10;}
            
			class ACE_morphine {
                displayName = "ACE_morphine";
                description = "ACE_morphine";
                amount = 10;
                price = 1500;
                stock = 10;}

		class Weapons {
            kindOf = "Weapons";
            displayName = "Weapons";

            //items of this category:
            class CUP_srifle_LeeEnfield {
                displayName = "test";
                description = "test";
                price = 2500;
                stock = 5;}
				
            };
        };
	};
};
```

**Comment by McDiod** [comment]
Hi,
this is hard to read because of the formatting, but on first glance it looks like

1. ~~`class weapons` is missing the closing bracket~~ nvm
2. `class weapons` is a child of `class items`, when it needs to be a sibling

**Comment by xzagrx** [comment]
> 
> 
> Hi,
> this is hard to read because of the formatting, but on first glance it looks like
> 
>     1. ~`class weapons` is missing the closing bracket~ nvm
> 
>     2. `class weapons` is a child of `class items`, when it needs to be a sibling

hm, for some reason it's dosen't work, can you please if it's not hard for you show me the example? :( it is my first time to do shop in description, how can i properly make it sibling?

**Comment by McDiod** [comment]
You have 

```
class items {
    class weapons {

    };
};
```

you need

```
class items {

};
class weapons {

};
```

**Comment by xzagrx** [comment]
hm, when i'm trying to separate them and do as you told me to do, it's say that i miss } somewhere, maybe it will be better if you show some kind of example mission where you can buy more that two items and weapons from the shop?

**Comment by nomisum** [comment]
would be helpful if you post the complete description.ext, maybe as a gist

![gist](https://user-images.githubusercontent.com/500164/82730133-cb518e00-9cfd-11ea-96b2-351040db6252.PNG)

missing brackets is a trivial error. count opening ones and closing ones and think about what should be encapsulated. use an editor with syntax highlighting, it helps tremendously.

**Comment by xzagrx** [comment]
nevermind, i figure it out! 👍 thanks anyway for the help, it was indeed missing brakets X)
