### ISSUE TITLE
[Question] Selling list?

### ISSUE THREAD

**Issue by TenuredCLOUD** [gruppe-adler/grad-listBuymenu#26]
Anyway to make a Sell list? Or is this strictly buying? 

I really like the idea of this system and can use this in endless ways

**Comment by McDiod** [comment]
This is buying only.

Selling should not be too hard of a feature to add, but I will most likely never personally implement it. Open for pull requests though.

**Comment by TenuredCLOUD** [comment]
No worries, I can still use it for a TON of things, keep up the good work, I love your guy’s systems!
