### ISSUE TITLE
profileNamespace instead of missionNamespace

### ISSUE THREAD

**Issue by BSherb** [gruppe-adler/grad-listBuymenu#27]
This is more of a request/question than it is a bug.

Is there some way to use this in a more persistent manner? Saving said values between a string of missions?

I did attempt to swap all missionNamespace instances in the code with profileNamespace, but even running saveProfileNamespace; didn't manage to allow the information to be used after a server restart.

**Comment by nomisum** [comment]
did you check https://github.com/gruppe-adler/grad-persistence ? its said to support listBuyMenu

**Comment by BSherb** [comment]
Oh no! I didn't see that at all! I'll give it a look and see what happens with everything. Thank you, I'll definitely get back to you.

**Comment by McDiod** [comment]
Out of the box, `grad-persistence` can only save player/team money. Are you trying to save anything else?

**Comment by BSherb** [comment]
Originally just used it to save the money, however I did a slight test and it did save unit positions/playermade fobs.
So I think it's working good for other things as well.
