### ISSUE TITLE
Items in Objekte ohne Inventory verschwinden

### ISSUE THREAD

**Issue by Salbei2500** [gruppe-adler/grad-listBuymenu#9]
Wenn man etwas kauft, dessen slot schon besetzt ist wird es im Inventar des Dealers abgelegt. Hat der Dealer nun kein Inventar verschwindet das Objekt einfach!

**Comment by McDiod** [comment]
Dafür kann man als [cargospace](https://github.com/gruppe-adler/grad-listBuymenu#access-menu) eine Position statt einem Objekt angeben. Der gekaufte Gegenstand wird dann auf der Position in einen Groundweaponholder abgelegt. 

[Neu](https://github.com/gruppe-adler/grad-listBuymenu/releases/tag/0.2.3): Die Position ist jetzt PositionASL, so dass man die Höhe genauer bestimmen kann - z.B. um zu verhindern, dass der Weaponholder unter dem Boden spawnt, so wie in Urban Ops letztens.
